version: '3.7'
services:
  lumen-api-sqlsrv:
    image: "jyeany/php-sqlsrv-xdebug:latest"
    container_name: lumen-api-sqlsrv
    ports:
      - "5000:80"
    volumes:
      - ./src:/var/www/html/site 
    depends_on:
      - lumen-sqlsrv 
  lumen-sqlsrv:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: "lumen-sqlsrv"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: SaLumenSqlSrv1234
      ACCEPT_EULA: Y